const sections = [
    'MainConcepts_01HelloWorld',
    'MainConcepts_02IntroducingJSX',
    'MainConcepts_03RenderingElements',
    'MainConcepts_04ComponentsAndProps',
    'MainConcepts_05StateAndLifecycle',
    'MainConcepts_06HandlingEvents',
    'MainConcepts_07ConditionalRendering',
    'MainConcepts_08ListsAndKeys',
    'MainConcepts_09Forms',
    'MainConcepts_10LiftingStateUp',
    'MainConcepts_11CompositionVsInheritance',
    'MainConcepts_12ThinkingInReact',
    'AdvancedGuides_01Accessibility',
    'AdvancedGuides_02CodeSplitting',
    'AdvancedGuides_03Context',
    'AdvancedGuides_04ErrorBoundaries',
    'AdvancedGuides_05ForwardingRefs',
    'AdvancedGuides_06Fragments',
    'AdvancedGuides_07HigherOrderComponents',
    'AdvancedGuides_08IntegratingWithOtherLibraries',
    'AdvancedGuides_09JSXInDepth',
    'AdvancedGuides_10OptimizingPerformance',
    'AdvancedGuides_11Portals',
    'AdvancedGuides_12Profiler',
    'AdvancedGuides_13ReactWithoutES6',
];

module.exports = sections;